### ISSUE TITLE
Üleliigsed tühikud failis tmorftrtabel.txt

### ISSUE THREAD

**Issue by paultammo** [EstSyntax/EstCG#4]
Tühikud @ ees faili tmorftrtabel.txt ridadel 1, 32, 320, 520, 550, 643 põhjustavad tehnilisi raskusi. Kas need saaks eemaldada?

Üks üleliigne tühik näib olevat ka real 464, aga see ei sega.

**Comment by kailimp** [comment]
Tühikud on eemaldatud.

**Comment by paultammo** [comment]
Suurepärane!
